blackportal-ai/portal

- src/layouts/Layout.astro
- src/pages/index.astro
> Added SEO description

- src/components/Footer/index.tsx
> Added social links to footer

- package-lock.json
- package.json
- src/components/sections/home/Hero/index.tsx
- src/layouts/Layout.astro
- tailwind.config.mjs
> Change font to Chakra Petch

- src/data/sidebar.ts
> Added Contributors menu section

- src/components/Footer/index.tsx
- src/layouts/MDXPageLayout.astro
- src/pages/privacy-policy.mdx
- src/pages/toc.mdx
> Added Terms of Conduct & Privacy Policy pages

- src/data/social-links.ts
> Fix GitHub link

- package-lock.json
- package.json
- src/components/forms/ContactForm/index.tsx
- src/components/ui/Form/index.tsx
- src/components/ui/Label/index.tsx
- src/components/ui/Textarea/index.tsx
- src/data/main-menu.ts
- src/pages/contact.astro
> Add contact page

- src/components/Footer/index.tsx
- src/data/footer-links.ts
> Update footer - add more links

- package-lock.json
- package.json
- src/components/Navbar/MobileNav.tsx
- src/components/Navbar/index.tsx
- src/components/sections/about/Team/index.tsx
- src/components/sections/about/Values/index.tsx
- src/components/sections/home/Hero/WelcomeMessage.tsx
- src/components/ui/Avatar/index.tsx
- src/data/footer-links.ts
- src/data/main-menu.ts
- src/data/team.ts
- src/data/values.ts
- src/pages/about.astro
- src/pages/contact.astro
> Add about page

- src/components/sections/about/Team/index.tsx
- src/data/team.ts
> Added team members positions

- src/content/delta/docs/architecture.mdx
- src/content/delta/docs/backends.mdx
- src/content/delta/docs/comparison.mdx
- src/content/delta/docs/customization.mdx
- src/content/delta/docs/datasets.mdx
- src/content/delta/docs/development-guidelines.mdx
- src/content/delta/docs/distributed-training.mdx
- src/content/delta/docs/integration.mdx
- src/content/delta/docs/release-checklist.mdx
- src/content/delta/docs/supported-features.mdx
- src/content/delta/docs/vision.mdx
- src/data/roadmap.ts
- src/data/sidebar.ts
> Updating docs

- src/data/roadmap.ts
Let me know if this sounds good or we need to include more stuff.
> Updating roadmap for Delta

- src/components/Footer/index.tsx
- src/components/Navbar/MobileNav.tsx
- src/components/Navbar/index.tsx
- src/data/social-links.ts
> Add YouTube link

- src/components/sections/about/AboutMessage/index.tsx
- src/pages/about.astro
> Add typewriter effect to about page title

- src/components/Footer/index.tsx
> Move company section in footer to left

- src/components/icons/SevallaLogo.tsx
- src/components/sections/brand/BrandList/index.tsx
- src/components/sections/brand/BrandMessage/index.tsx
- src/data/brand.ts
- src/data/footer-links.ts
- src/pages/brand.astro
- src/types/brand.ts
> Add brand page

- src/pages/index.astro
> Remove Get Started section from home page

- src/components/sections/about/Values/index.tsx
- src/data/values.ts
> Added icons to values

- .github/dependabot.yml
- package-lock.json
- package.json
- Downgrade tailwind-merge for support tailwindcss v3
- Add to dependabot ignore tailwindcss & tailwind-merge deps
> Add twcss to ignore

- src/data/team.ts
> Added team member

- src/components/Footer/index.tsx
- src/components/sections/home/Features/FeatureCard.tsx
- src/components/sections/home/Features/index.tsx
- src/components/sections/home/Hero/index.tsx
- src/components/sections/home/Roadmap/index.tsx
- src/content.config.ts
- src/data/features.ts
- src/data/footer-links.ts
- src/data/roadmap.ts
- src/data/sidebar.ts
- src/pages/horizon/docs/[id].astro
- src/pages/horizon/docs/index.astro
- src/pages/nebula/docs/[id].astro
- src/styles/globals.css
- src/types/sidebar.ts
> Add horizon project
